media:
  input: wp-content/uploads
  output: /wp-content/uploads

content:
  - name: planned_litters
    label: Planned Litters
    type: file
    path: content/planned-litters.md
    fields:
      - name: title
        label: Page Title
        type: string

      - name: body
        label: Page Content
        type: rich-text